const inventory = [];
const inventoryObjects = [];
const maxItems = 4;

const objects = document.querySelectorAll(".collectible");
const slots = document.querySelectorAll(".slot");

// Map of object combinations to archetype URLs
const archetypeMap = {
  // 01. Default (if no match found)
  "alien-lighter-moeda":
    "https://www.researchcatalogue.net/view/4308270/4494897",

  // 2. The Nostalgic — tickets, papers, older objects
  "bilhete-finance-oculista-postal":
    "https://www.researchcatalogue.net/view/4308270/4497179",
  "bilhete-forum-oculista-postal":
    "https://www.researchcatalogue.net/view/4308270/4497179",

  // 3. The Fugitive — lost keys, abandoned umbrellas, coins
  "dollar-globeCoin-remote-umbrella":
    "https://www.researchcatalogue.net/view/4308270/4497204",
  "godCoin-lighter-umbrella-wallet":
    "https://www.researchcatalogue.net/view/4308270/4497204",

  // 4. The Collector — a single earring, wristwatch, button, pen
  "anel-caneta-clock-dente":
    "https://www.researchcatalogue.net/view/4308270/4497232",
  "anel-caneta-pulseira-socks":
    "https://www.researchcatalogue.net/view/4308270/4497232",

  // 5. The Romantic — wedding ring, turtle, polaroid
  "anel-pulseira-tartaruga-velas":
    "https://www.researchcatalogue.net/view/4308270/4498632",
  "anel-cartaoSanto-polaroid-velas":
    "https://www.researchcatalogue.net/view/4308270/4498632",

  // 6. The Observer — documents, glasses, receipts
  "cartaoVisa-finance-oculista-sunglasses":
    "https://www.researchcatalogue.net/view/4308270/4498651",
  "finance-oculista-polaroid-sunglasses":
    "https://www.researchcatalogue.net/view/4308270/4498651",

  // 7. The Chaotic — cracked objects, tangled chargers, coins
  "carregador-coin-dollar-remote":
    "https://www.researchcatalogue.net/view/4308270/4498685",
  "carregador-coin-wallet-socks":
    "https://www.researchcatalogue.net/view/4308270/4498685",

  // 8. The Melancholic — time, forgotten things
  "clock-oculista-polaroid-velas":
    "https://www.researchcatalogue.net/view/4308270/4498707",
  "cartaoSanto-clock-forum-postal":
    "https://www.researchcatalogue.net/view/4308270/4498707",

  // 9. The Hunter — mystery, searching, hidden narratives
  "alien-backpack-finance-mochila":
    "https://www.researchcatalogue.net/view/4308270/4498735",
  "alien-remote-umbrella-wallet":
    "https://www.researchcatalogue.net/view/4308270/4498735",

  // 10. The Performer — identity, appearance, transformation
  "anel-cartaoSanto-cartaoVisa-sunglasses":
    "https://www.researchcatalogue.net/view/4308270/4498803",
  "bilhete-guardanapo-pulseira-sunglasses":
    "https://www.researchcatalogue.net/view/4308270/4498803",
};

// Normalize archetypeMap keys to ensure consistent matching regardless of selection order bc I am lazy to re-write all combinations manually
const normalizedArchetypeMap = {};

Object.entries(archetypeMap).forEach(([key, value]) => {
  const normalizedKey = key.split("-").sort().join("-");
  normalizedArchetypeMap[normalizedKey] = value;
});

// event listener for each object
objects.forEach((object) => {
  object.addEventListener("click", () => {
    if (inventory.length >= maxItems) return;

    const image = object.dataset.image;
    const objectName = object.dataset.object;

    inventory.push(image);
    inventoryObjects.push(objectName);

    updateInventory();

    object.style.opacity = "0";
    object.style.pointerEvents = "none";
  });
});

// function to update inventory display
function updateInventory() {
  slots.forEach((slot, index) => {
    slot.innerHTML = "";

    if (inventory[index]) {
      const img = document.createElement("img");
      img.src = inventory[index];

      slot.appendChild(img);
    }
  });

  // check if inventory is full and redirect to appropriate archetype
  if (inventory.length >= maxItems) {
    setTimeout(() => {
      const archetypeURL = getArchetypeURL(inventoryObjects);
      window.location.href = archetypeURL;
    }, 1200);
  }
}

// Alphabetize key generated by user to ensure consistent matching regardless of selection order
function normalizeCombination(arr) {
  return [...arr].sort().join("-");
}

// function to determine archetype URL based on collected objects
function getArchetypeURL(objects) {
  const combination = normalizeCombination(objects);

  // debug: log the combination to verify correct key generation
  console.log(combination);

  // Return matching URL, or first archetype as default
  return (
    normalizedArchetypeMap[combination] ||
    Object.values(normalizedArchetypeMap)[0] ||
    "https://www.researchcatalogue.net/view/4308270/4494897"
  );
}

// persist inventory in localStorage
localStorage.setItem("inventory", JSON.stringify(inventory));
